import Navbar from "@/components/Navbar";
import TitleBar from "@/components/TitleBar";
import { AuthProvider } from "@/context/AuthProvider";
import { Geist, Geist_Mono, Montserrat, Poppins, Inter } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import { SkeletonTheme } from 'react-loading-skeleton';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const monteserrat = Montserrat({
  variable: "--font-monteserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${monteserrat.variable} ${inter.variable}`}>
        <SkeletonTheme baseColor="#E0E0E0" highlightColor="#525252" duration={3}>
          <AuthProvider>
            <div className="container">
              <TitleBar />
              <div className="chatContainer">
                <Navbar />
                <Toaster position="top-right" />
                {children}
              </div>
            </div>
          </AuthProvider>
        </SkeletonTheme>
      </body>
    </html>
  );
}
